import { ImageSourcePropType } from "react-native";

const images: { [key: string]: { uri: ImageSourcePropType } } = {
    SPIRITISM: {
        uri: require("../../assets/images/powers/SPIRITISM.png")
    },
    CONTAMINATION: {
        uri: require("../../assets/images/powers/CONTAMINATION.png")
    },
    INSOMNIA: {
        uri: require("../../assets/images/powers/INSOMNIA.png")
    },
    WEREWOLF: {
        uri: require("../../assets/images/roles/WEREWOLF.png")
    },
    HUMAN: {
        uri: require("../../assets/images/roles/HUMAN.png")
    },
    CLAIRVOYANCE: {
        uri: require("../../assets/images/powers/CLAIRVOYANCE.png")
    },
    UNKNOWN: {
        uri: require("../../assets/images/UNKNOWN.png")
    }
};

export function getImageSource(name: string): { uri: ImageSourcePropType } {
    if (images[name]) return images[name];
    console.log(`Image ${name} not found`);
    return images.UNKNOWN;
}

export const backgroundFrames = [
    require("../../assets/images/background/frame_000.gif"),
    require("../../assets/images/background/frame_001.gif"),
    require("../../assets/images/background/frame_002.gif"),
    require("../../assets/images/background/frame_003.gif"),
    require("../../assets/images/background/frame_004.gif"),
    require("../../assets/images/background/frame_005.gif"),
    require("../../assets/images/background/frame_006.gif"),
    require("../../assets/images/background/frame_007.gif"),
    require("../../assets/images/background/frame_008.gif"),
    require("../../assets/images/background/frame_009.gif"),
    require("../../assets/images/background/frame_010.gif"),
    require("../../assets/images/background/frame_011.gif"),
    require("../../assets/images/background/frame_012.gif"),
    require("../../assets/images/background/frame_013.gif"),
    require("../../assets/images/background/frame_014.gif"),
    require("../../assets/images/background/frame_015.gif"),
    require("../../assets/images/background/frame_016.gif"),
    require("../../assets/images/background/frame_017.gif"),
    require("../../assets/images/background/frame_018.gif"),
    require("../../assets/images/background/frame_019.gif"),
    require("../../assets/images/background/frame_020.gif"),
    require("../../assets/images/background/frame_021.gif"),
    require("../../assets/images/background/frame_022.gif"),
    require("../../assets/images/background/frame_023.gif"),
    require("../../assets/images/background/frame_024.gif"),
    require("../../assets/images/background/frame_025.gif"),
    require("../../assets/images/background/frame_026.gif"),
    require("../../assets/images/background/frame_027.gif"),
    require("../../assets/images/background/frame_028.gif"),
    require("../../assets/images/background/frame_029.gif"),
    require("../../assets/images/background/frame_030.gif"),
    require("../../assets/images/background/frame_031.gif"),
    require("../../assets/images/background/frame_032.gif"),
    require("../../assets/images/background/frame_033.gif"),
    require("../../assets/images/background/frame_034.gif"),
    require("../../assets/images/background/frame_035.gif"),
    require("../../assets/images/background/frame_036.gif"),
    require("../../assets/images/background/frame_037.gif"),
    require("../../assets/images/background/frame_038.gif"),
    require("../../assets/images/background/frame_039.gif"),
    require("../../assets/images/background/frame_040.gif"),
    require("../../assets/images/background/frame_041.gif"),
    require("../../assets/images/background/frame_042.gif"),
    require("../../assets/images/background/frame_043.gif"),
    require("../../assets/images/background/frame_044.gif"),
    require("../../assets/images/background/frame_045.gif"),
    require("../../assets/images/background/frame_046.gif"),
    require("../../assets/images/background/frame_047.gif"),
    require("../../assets/images/background/frame_048.gif"),
    require("../../assets/images/background/frame_049.gif"),
    require("../../assets/images/background/frame_050.gif"),
    require("../../assets/images/background/frame_051.gif"),
    require("../../assets/images/background/frame_052.gif"),
    require("../../assets/images/background/frame_053.gif"),
    require("../../assets/images/background/frame_054.gif"),
    require("../../assets/images/background/frame_055.gif"),
    require("../../assets/images/background/frame_056.gif"),
    require("../../assets/images/background/frame_057.gif"),
    require("../../assets/images/background/frame_058.gif"),
    require("../../assets/images/background/frame_059.gif"),
    require("../../assets/images/background/frame_060.gif"),
    require("../../assets/images/background/frame_061.gif"),
    require("../../assets/images/background/frame_062.gif"),
    require("../../assets/images/background/frame_063.gif"),
    require("../../assets/images/background/frame_064.gif"),
    require("../../assets/images/background/frame_065.gif"),
    require("../../assets/images/background/frame_066.gif"),
    require("../../assets/images/background/frame_067.gif"),
    require("../../assets/images/background/frame_068.gif"),
    require("../../assets/images/background/frame_069.gif"),
    require("../../assets/images/background/frame_070.gif"),
    require("../../assets/images/background/frame_071.gif"),
    require("../../assets/images/background/frame_072.gif"),
    require("../../assets/images/background/frame_073.gif"),
    require("../../assets/images/background/frame_074.gif"),
    require("../../assets/images/background/frame_075.gif"),
    require("../../assets/images/background/frame_076.gif"),
    require("../../assets/images/background/frame_077.gif"),
    require("../../assets/images/background/frame_078.gif"),
    require("../../assets/images/background/frame_079.gif"),
    require("../../assets/images/background/frame_080.gif"),
    require("../../assets/images/background/frame_081.gif"),
    require("../../assets/images/background/frame_082.gif"),
    require("../../assets/images/background/frame_083.gif"),
    require("../../assets/images/background/frame_084.gif"),
    require("../../assets/images/background/frame_085.gif"),
    require("../../assets/images/background/frame_086.gif"),
    require("../../assets/images/background/frame_087.gif"),
    require("../../assets/images/background/frame_088.gif"),
    require("../../assets/images/background/frame_089.gif"),
    require("../../assets/images/background/frame_090.gif"),
    require("../../assets/images/background/frame_091.gif"),
    require("../../assets/images/background/frame_092.gif"),
    require("../../assets/images/background/frame_093.gif"),
    require("../../assets/images/background/frame_094.gif"),
    require("../../assets/images/background/frame_095.gif"),
    require("../../assets/images/background/frame_096.gif"),
    require("../../assets/images/background/frame_097.gif"),
    require("../../assets/images/background/frame_098.gif"),
    require("../../assets/images/background/frame_099.gif"),
    require("../../assets/images/background/frame_100.gif"),
    require("../../assets/images/background/frame_101.gif"),
    require("../../assets/images/background/frame_102.gif"),
    require("../../assets/images/background/frame_103.gif"),
    require("../../assets/images/background/frame_104.gif"),
    require("../../assets/images/background/frame_105.gif"),
    require("../../assets/images/background/frame_106.gif"),
    require("../../assets/images/background/frame_107.gif"),
    require("../../assets/images/background/frame_108.gif"),
    require("../../assets/images/background/frame_109.gif"),
    require("../../assets/images/background/frame_110.gif"),
    require("../../assets/images/background/frame_111.gif"),
    require("../../assets/images/background/frame_112.gif"),
    require("../../assets/images/background/frame_113.gif"),
    require("../../assets/images/background/frame_114.gif"),
    require("../../assets/images/background/frame_115.gif"),
    require("../../assets/images/background/frame_116.gif"),
    require("../../assets/images/background/frame_117.gif"),
    require("../../assets/images/background/frame_118.gif"),
    require("../../assets/images/background/frame_119.gif"),
    require("../../assets/images/background/frame_120.gif"),
    require("../../assets/images/background/frame_121.gif"),
    require("../../assets/images/background/frame_122.gif"),
    require("../../assets/images/background/frame_123.gif"),
    require("../../assets/images/background/frame_124.gif"),
    require("../../assets/images/background/frame_125.gif"),
    require("../../assets/images/background/frame_126.gif"),
    require("../../assets/images/background/frame_127.gif"),
    require("../../assets/images/background/frame_128.gif"),
    require("../../assets/images/background/frame_129.gif"),
    require("../../assets/images/background/frame_130.gif"),
    require("../../assets/images/background/frame_131.gif"),
    require("../../assets/images/background/frame_132.gif"),
    require("../../assets/images/background/frame_133.gif"),
    require("../../assets/images/background/frame_134.gif"),
    require("../../assets/images/background/frame_135.gif"),
    require("../../assets/images/background/frame_136.gif"),
    require("../../assets/images/background/frame_137.gif"),
    require("../../assets/images/background/frame_138.gif"),
    require("../../assets/images/background/frame_139.gif"),
    require("../../assets/images/background/frame_140.gif"),
    require("../../assets/images/background/frame_141.gif"),
    require("../../assets/images/background/frame_142.gif"),
    require("../../assets/images/background/frame_143.gif"),
    require("../../assets/images/background/frame_144.gif"),
    require("../../assets/images/background/frame_145.gif"),
    require("../../assets/images/background/frame_146.gif"),
    require("../../assets/images/background/frame_147.gif"),
    require("../../assets/images/background/frame_148.gif"),
    require("../../assets/images/background/frame_149.gif"),
    require("../../assets/images/background/frame_150.gif"),
    require("../../assets/images/background/frame_151.gif"),
    require("../../assets/images/background/frame_152.gif"),
    require("../../assets/images/background/frame_153.gif"),
    require("../../assets/images/background/frame_154.gif"),
    require("../../assets/images/background/frame_155.gif"),
    require("../../assets/images/background/frame_156.gif"),
    require("../../assets/images/background/frame_157.gif"),
    require("../../assets/images/background/frame_158.gif"),
    require("../../assets/images/background/frame_159.gif"),
    require("../../assets/images/background/frame_160.gif"),
    require("../../assets/images/background/frame_161.gif"),
    require("../../assets/images/background/frame_162.gif"),
    require("../../assets/images/background/frame_163.gif"),
    require("../../assets/images/background/frame_164.gif"),
    require("../../assets/images/background/frame_165.gif"),
    require("../../assets/images/background/frame_166.gif"),
    require("../../assets/images/background/frame_167.gif"),
    require("../../assets/images/background/frame_168.gif"),
    require("../../assets/images/background/frame_169.gif"),
    require("../../assets/images/background/frame_170.gif"),
    require("../../assets/images/background/frame_171.gif"),
    require("../../assets/images/background/frame_172.gif"),
    require("../../assets/images/background/frame_173.gif"),
    require("../../assets/images/background/frame_174.gif")
];

export { images };
